# SPDX-License-Identifier: LGPL-3.0-or-later

from .base import (
    AMOUNT_OF_SUBSTANCE,
    DIMENSIONLESS,
    ELECTRIC_CURRENT,
    LENGTH,
    LUMINOUS_INTENSITY,
    MASS,
    TIME,
)

# === The 22¹ SI units with special name and symbols ===
# ¹21 actually, Celsius temperature is missing because it has to be convert from kelvin

PLANE_ANGLE = DIMENSIONLESS
SOLID_ANGLE = PLANE_ANGLE**2
FREQUENCY = TIME**-1
FORCE = MASS * LENGTH / TIME**2
PRESSURE = FORCE / LENGTH**2
STRESS = FORCE / LENGTH**2  # equal to pressure
ENERGY = FORCE * LENGTH
WORK = FORCE * LENGTH  # equal to energy
AMOUNT_OF_HEAT = FORCE * LENGTH  # equal to energy and work
POWER = ENERGY / TIME
RADIANT_FLUX = ENERGY / TIME  # equal to power
ELECTRIC_CHARGE = TIME * ELECTRIC_CURRENT
ELECTRIC_POTENTIAL_DIFFERENCE = POWER / ELECTRIC_CURRENT
ELECTRICAL_RESISTANCE = ELECTRIC_POTENTIAL_DIFFERENCE / ELECTRIC_CURRENT
ELECTRICAL_CONDUCTANCE = ELECTRIC_CURRENT / ELECTRIC_POTENTIAL_DIFFERENCE
CAPACITANCE = ELECTRIC_CHARGE / ELECTRIC_POTENTIAL_DIFFERENCE
MAGNETIC_FLUX = ELECTRIC_POTENTIAL_DIFFERENCE * TIME
INDUCTANCE = MAGNETIC_FLUX / ELECTRIC_CURRENT
MAGNETIC_FLUX_DENSITY = MAGNETIC_FLUX / LENGTH**2
LUMINOUS_FLUX = LUMINOUS_INTENSITY * SOLID_ANGLE
ILLUMINANCE = LUMINOUS_FLUX / LENGTH**2
RADIONUCLIDE_ACTIVITY = TIME**-1
ABSORBED_DOSE = ENERGY / MASS
KERMA = ENERGY / MASS  # equal to absorbed dose
DOSE_EQUIVALENT = ENERGY / MASS  
CATALYTIC_ACTIVITY = AMOUNT_OF_SUBSTANCE / TIME

# TODO: complete all the derived dimensions