# SPDX-License-Identifier: LGPL-3.0-or-later

from .base import (
    AMOUNT_OF_SUBSTANCE,
    ELECTRIC_CURRENT,
    LENGTH,
    LUMINOUS_INTENSITY,
    MASS,
    THERMODYNAMIC_TEMPERATURE,
    TIME,
)

T = TIME
L = LENGTH
M = MASS
I = ELECTRIC_CURRENT
THETA = THERMODYNAMIC_TEMPERATURE
N = AMOUNT_OF_SUBSTANCE
J = LUMINOUS_INTENSITY