# SPDX-License-Identifier: LGPL-3.0-or-later

from .fundamental import (
    AMOUNT_OF_SUBSTANCE,
    DIMENSIONLESS,
    ELECTRIC_CURRENT,
    LENGTH,
    LUMINOUS_INTENSITY,
    MASS,
    TIME,
)

RADIAN = DIMENSIONLESS
STERADIAN = DIMENSIONLESS
FREQUENCY = TIME ** -1
ACCELERATION = LENGTH / TIME ** 2
FORCE = MASS * ACCELERATION
PRESSURE = FORCE / LENGTH ** 2
STRESS = PRESSURE
ENERGY = FORCE * LENGTH
WORK = ENERGY
AMOUNT_OF_HEAT = ENERGY
POWER = ENERGY / TIME
RADIANT_FLUX = POWER
ELECTRIC_CHARGE = TIME * ELECTRIC_CURRENT
ELECTRIC_POTENTIAL_DIFFERENCE = POWER / ELECTRIC_CURRENT
ELECTRICAL_RESISTANCE = ELECTRIC_POTENTIAL_DIFFERENCE / ELECTRIC_CURRENT
ELECTRICAL_CONDUCTANCE = ELECTRIC_CURRENT / ELECTRIC_POTENTIAL_DIFFERENCE
CAPACITANCE = ELECTRIC_CHARGE / ELECTRIC_POTENTIAL_DIFFERENCE
MAGNETIC_FLUX = ELECTRIC_POTENTIAL_DIFFERENCE * TIME
INDUCTANCE = MAGNETIC_FLUX / ELECTRIC_CURRENT
MAGNETIC_FLUX_DENSITY = MAGNETIC_FLUX / LENGTH ** 2
LUMEN = LUMINOUS_INTENSITY * STERADIAN
LUX = LUMEN / LENGTH ** 2
BECQUEREL = FREQUENCY
GRAY = ENERGY / MASS
SIEVERT = GRAY
KATAL = AMOUNT_OF_SUBSTANCE / TIME